version: '3'

services:
  web:
    build: .
    command: sh -c "python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=Quresh_App.settings
      - USE_DOCKER=True
      - MONGO_DATABASE_NAME=quresh_db
      - MONGO_HOST=db
      - MONGO_PORT=27017
    depends_on:
      - db

  db:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  static_volume:
  media_volume:
  excel_to_db_volume:
  excel_to_pdf_volume:
  mongodb_data: