# Generated by Django 3.2.23 on 2024-09-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_editor', '0003_auto_20240930_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelimage',
            name='information',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='excelimage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
